about:
  name: WillbeNpmPublishTest
  description: >-
    Module for testing. This module is a test asset and not intended to be used
    with another purpose.
  version: 0.0.1
  enabled: 1
  interpreters:
    - njs >= 10.0.0
    - chrome >= 60.0.0
    - firefox >= 60.0.0
  keywords:
    - willbe
    - test
  license: MIT
  author: Kostiantyn Wandalen <wanalen@01.school>
  contributors:
    - Kostiantyn Wandalen <wanalen@01.school>
    - Kryvoruchko Dmytro <dm.vict.kr@gmail.com>
  npm.name: willbe.npm.publish.test
  npm.scripts:
    test: 'wtest .run proto/** rapidity:-3'
    docgen: wdocgen proto
path:
  repository: 'git+https:///github.com/wtools-bot/WillbeNpmPublishTest.git'
  origins:
    - 'git+https:///github.com/wtools-bot/WillbeNpmPublishTest.git'
    - 'npm:///willbe.npm.publish.test'
  bugtracker: 'https:///github.com/wtools-bot/WillbeNpmPublishTest/issues'
step:

  proto.export:
    inherit: module.export
    export: 'path::export'
    tar: 0
    criterion:
      content: proto
  doc.export:
    inherit: module.export
    export: 'path::doc'
    tar: 0
    criterion:
      content: doc
  npm.export:
    inherit: module.export
    export: out.npm
    tar: 0
    criterion:
      content: npm
  npm.publish:
    shell: npm publish

build:
  proto.export:
    criterion:
      content: proto
      export: 1
    steps:
      - 'step::proto.export'
  doc.export:
    criterion:
      content: doc
      export: 1
    steps:
      - 'step::doc.export'
  npm.export:
    criterion:
      content: npm
      export: 1
    steps:
      - 'step::npm.publish'
  export:
    criterion:
      default: 1
      export: 1
    steps:
      - 'build::proto.export'
